// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a864ff28-c996-4946-a7a0-9381157e465b";

const char SSID[]               = "SSID";    // Network SSID (name)
const char PASS[]               = "";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "XjXcyZWfjM4153tyQW?#TorDo";    // Secret device password

void onWaterLevelChange();

int water_Level;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(water_Level, READWRITE, ON_CHANGE, onWaterLevelChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
