/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/38603ecc-0043-4b50-91ab-740eba55c764 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int water_Level;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define TRIG_PIN D1
#define ECHO_PIN D2
#define PUMP D3
#define BUZZER D5

unsigned long previous_millis = 0;

void setup() {
  // Initialize serial and wait for port to open:
  pinMode(BUZZER, OUTPUT);
  pinMode(PUMP, OUTPUT);
  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);
  // Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  // setDebugMessageLevel(2);
  // ArduinoCloud.printDebugInfo();
  water_Level = 100;
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  if (millis() - previous_millis > 1000) {
    digitalWrite(TRIG_PIN, LOW);
    delayMicroseconds(2);
    digitalWrite(TRIG_PIN, HIGH);
    delayMicroseconds(10);
    digitalWrite(TRIG_PIN, LOW);
    int duration = pulseIn(ECHO_PIN, HIGH);
    int distance = (duration / 2) / 29.1;
    distance = map(distance, 5, 17, 100, 0);

    if (distance > 100) {
      distance = 100;
    } else if (distance < 0) {
      distance = 0;
    }

    water_Level = distance;
    previous_millis = millis();
  }

  if (water_Level > 80) {
    digitalWrite(BUZZER, LOW);
    digitalWrite(PUMP, LOW);
  } else {
    digitalWrite(BUZZER, HIGH);
    digitalWrite(PUMP, HIGH);
  }
}


/*
  Since WaterLevel is READ_WRITE variable, onWaterLevelChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWaterLevelChange() {
  // Add your code here to act upon WaterLevel change
}
